# This is a basic workflow that is manually triggered

name: Pages Deployment

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
     - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy_job:
    runs-on: ubuntu=18.04
    steps:
    - name: deploy to production branch
      run: ./deploy.sh
